import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.2"

    const val android_arch_navigation: String = "1.0.0"

    const val androidx_test_espresso: String = "3.2.0"

    const val com_squareup_retrofit2: String = "2.6.2"

    const val androidx_databinding: String = "3.5.2"

    const val org_jetbrains_kotlin: String = "1.3.50"

    const val com_squareup_moshi: String = "1.9.1"

    const val androidx_fragment: String = "1.1.0"

    const val org_robolectric: String = "4.3.1"

    const val androidx_room: String = "2.2.1"

    const val androidx_test: String = "1.2.0"

    const val org_jacoco: String = "0.7.9"

    const val io_mockk: String = "1.9.3"

    const val org_koin: String = "2.0.1"

    const val androidx_arch_core_core_testing: String = "2.1.0"

    const val com_android_tools_build_gradle: String = "3.5.2"

    const val androidx_core_core_ktx: String = "1.1.0"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val retrofit2_kotlin_coroutines_adapter: String = "0.9.2"

    const val lifecycle_extensions: String = "2.1.0"

    const val logging_interceptor: String = "4.2.2"

    const val constraintlayout: String = "1.1.3"

    const val mpandroidchart: String = "3.1.0"

    const val activity_ktx: String = "1.0.0"

    const val recyclerview: String = "1.0.0"

    const val lint_gradle: String = "26.5.2"

    const val appcompat: String = "1.1.0"

    const val junit_ktx: String = "1.1.1"

    const val material: String = "1.1.0-beta01"

    const val aapt2: String = "3.5.2-5435860"

    const val junit: String = "4.12"

    const val truth: String = "1.0"

    /**
     * Current version: "5.6.2"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.0"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
        id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
